[build]
  command = "BUILD_TARGET=spa vite build"
  publish = "dist/"

[[redirects]]
  from = "/googlecc82818152975814.html"
  to = "/googlecc82818152975814.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
