[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/googlecc82818152975814.html"
  to = "/googlecc82818152975814.html"
  status = 200
  force = true
